# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: diabetix
services:
  kc-postgres:
    container_name: diabetix-postgres
    image: postgres:17
    environment:
      POSTGRES_DB: ${KC_DB_URL_DATABASE}
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - ./keycloak/keycloak_pg_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - diabetix-net
volumes:
  keycloak_pg_data: